name: Publishing

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 => intel, macos-14 => ARM
        os: [macos-13, macos-14, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # NOTE: necessary for rebuilding native modules, see https://github.com/actions/runner/issues/2958
      - name: Install setuptools
        if: ${{ matrix.os != 'windows-latest' && matrix.os != 'macos-14' }}
        run: |
          sudo -H pip install setuptools

      # NOTE: installing "setuptools" will not fix the issue in "macos-14" runner, downgrade the python version which has "distutils" by default
      - uses: actions/setup-python@v5
        if: ${{ matrix.os == 'macos-14' }}
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish release for mac
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        env:
          # auto updates signing for mac app
          # see for more info: https://www.electron.build/code-signing.html
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn build:publish

      - name: Publish releases for windows and linux
        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn build:publish
