name: Publishing

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 => intel, macos-14 => ARM
        os: [macos-13, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish release for mac
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        env:
          # auto updates signing for mac app
          # see for more info: https://www.electron.build/code-signing.html
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # to publish an application to github releases
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn build:publish

      - name: Publish releases for windows and linux
        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest' }}
        env:
          # to publish an application to github releases
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn build:publish
